apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: xyz-axonius-connector
  namespace: xyz-axonius-connector
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: xyz-axonius-connector
    creationPolicy: Owner
  data:
  - secretKey: AXONIUS_KEY
    remoteRef:
      key: /cdm-data-pipeline/xyz/pipeline-core
      property: AXONIUS_KEY
  - secretKey: AXONIUS_SECRET
    remoteRef:
      key: /cdm-data-pipeline/xyz/pipeline-core
      property: AXONIUS_SECRET
  - secretKey: KAFKA_CA_CERT_ENCODED
    remoteRef:
      key: /cdm-data-pipeline/xyz/pipeline-core
      property: KAFKA_CA_CERT_ENCODED
  - secretKey: KAFKA_USERNAME
    remoteRef:
      key: /cdm-data-pipeline/xyz/pipeline-core
      property:  KAFKA_AXONIUSCONNECTOR_USERNAME
  - secretKey: KAFKA_PASSWORD
    remoteRef:
      key: /cdm-data-pipeline/xyz/pipeline-core
      property: KAFKA_AXONIUSCONNECTOR_PASSWORD