apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: xyz-quality-cdm-processor
  namespace: xyz-quality-cdm-processor
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: xyz-quality-cdm-processor
    creationPolicy: Owner
  data:
  - secretKey: KAFKA_CA_CERT_ENCODED
    remoteRef:
      key: /cdm-data-pipeline/xyz/pipeline-core
      property: KAFKA_CA_CERT_ENCODED
  - secretKey: KAFKA_USERNAME
    remoteRef:
      key: /cdm-data-pipeline/xyz/pipeline-core
      property: KAFKA_QUALITYCDMPROCESSOR_USERNAME
  - secretKey: KAFKA_PASSWORD
    remoteRef:
      key: /cdm-data-pipeline/xyz/pipeline-core
      property: KAFKA_QUALITYCDMPROCESSOR_PASSWORD