{{- if or .Values.abc_cdm_data_pipeline.deploy_environment.local.enabled .Values.abc_cdm_data_pipeline.deploy_environment.eks.enabled }}
{{- if .Values.abc_cdm_data_pipeline.abc_quality_cdm_processor.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.abc_cdm_data_pipeline.abc_quality_cdm_processor.name }}
  namespace: {{ .Values.abc_cdm_data_pipeline.abc_quality_cdm_processor.namespace }}
data:
  {{- range $key, $value := .Values.abc_cdm_data_pipeline.abc_quality_cdm_processor.config }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}
{{- end }}