{{- range .Values.preInstallNamespaces }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecr-secret
  namespace: {{ . }}
  annotations:
    "helm.sh/resource-policy": "keep"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"{{ $.Values.aws.accountId }}.dkr.ecr.{{ $.Values.aws.region }}.amazonaws.com":{"username":"{{ `{{ .ECR_NAME }}` }}","password":"{{ `{{ .ECR_PASSWORD }}` }}","auth":"{{ `{{ printf "%s:%s" .ECR_NAME .ECR_PASSWORD | b64enc }}` }}"}}}'  
  data:
  - secretKey: ECR_PASSWORD
    remoteRef:
      key: /cdm-data-pipeline/pipeline-core
      property: ECR_PASSWORD
  - secretKey: ECR_NAME
    remoteRef:
      key: /cdm-data-pipeline/pipeline-core
      property: ECR_NAME
---
{{- end }}