{{- if or .Values.cdm_dictionary_connector.deploy_environment.local.enabled .Values.cdm_dictionary_connector.deploy_environment.eks.enabled }}
{{- if .Values.cdm_dictionary_connector.enabled }}
{{- if .Values.cdm_dictionary_connector.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cdm_dictionary_connector.serviceAccount.name }}
  namespace: {{ .Values.cdm_dictionary_connector.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.cdm_dictionary_connector.serviceAccount.roleArn }}
{{- end }}
{{- end }}
{{- end }}
