apiVersion: v1
kind: ConfigMap
metadata:
  name: abc-armis-processor
  namespace: abc-armis-processor
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka.cdm-kafka.svc.cluster.local:9071"
  KAFKA_SCHEMA_REGISTRY: "https://schemaregistry.cdm-kafka.svc.cluster.local:8081"
  ORGANIZATION_ID: "abc"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-armis-processor
  namespace: abc-armis-processor
  labels:
    app: abc-armis-processor
  annotations:
    configmap.reloader.stakater.com/reload: "abc-armis-processor"
    secret.reloader.stakater.com/reload: "abc-armis-processor"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abc-armis-processor
  template:
    metadata:
      labels:
        app: abc-armis-processor
    spec:
      containers:
        - name: abc-armis-processor
          image: ACCOUNTID.dkr.ecr.us-gov-east-1.amazonaws.com/pipeline-core:IMAGE_TAG
          imagePullPolicy: Always
          args: 
            - "dsp"
            - "process"
            - "armis"
            - "--group"
            - "process-armis"
          envFrom:
            - secretRef:
                name: abc-armis-processor
            - configMapRef:
                name: abc-armis-processor
          resources:
            limits:
              cpu: "1"
              memory: "3Gi"
      restartPolicy: Always
      imagePullSecrets:
        - name: ecr-secret