apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
  annotations:
    secret.reloader.stakater.com/reload: "{{ .Values.secrets.mdsClientErp }},{{ .Values.secrets.credential }},{{ .Values.secrets.mdsToken }}"
spec:
  license:
    secretRef: {{ .Values.kafka.license.secretRef }}
  replicas: {{ .Values.kafka.replicas }}
  dataVolumeCapacity: {{ .Values.kafka.dataVolumeCapacity }}
  configOverrides:
    server:
      {{- toYaml .Values.kafka.configOverrides.server | nindent 6 }}
    jvm:
      {{- toYaml .Values.kafka.configOverrides.jvm | nindent 6 }}
    log4j:
      {{- toYaml .Values.kafka.configOverrides.log4j | nindent 6 }}
  authorization:
    superUsers:
      {{- toYaml .Values.kafka.authorization.superUsers | nindent 6 }}
    type: {{ .Values.kafka.authorization.type }}
  dependencies:
    {{- toYaml .Values.kafka.dependencies | nindent 4 }}
  image:
    application: {{ .Values.kafka.image.application }}
    init: {{ .Values.kafka.image.init }}
  listeners:
    {{- toYaml .Values.kafka.listeners | nindent 4 }}
  services:
    mds:
      provider:
        type: {{ .Values.kafka.services.mds.provider.type }}
        ldap:
          address: {{ .Values.kafka.services.mds.provider.ldap.address }}
          authentication:
            type: {{ .Values.kafka.services.mds.provider.ldap.authentication.type }}
            simple:
              secretRef: {{ .Values.kafka.services.mds.provider.ldap.authentication.simple.secretRef }}
          configurations:
            {{- toYaml .Values.kafka.services.mds.provider.ldap.configurations | nindent 12 }}
          tls:
            enabled: {{ .Values.kafka.services.mds.provider.ldap.tls.enabled }}
      tls:
        enabled: {{ .Values.kafka.services.mds.tls.enabled }}
      tokenKeyPair:
        secretRef: {{ .Values.kafka.services.mds.tokenKeyPair.secretRef }}
  podTemplate:
    annotations:
      {{- toYaml .Values.kafka.podTemplate.annotations | nindent 6 }}
  tls:
    autoGeneratedCerts: {{ .Values.kafka.tls.autoGeneratedCerts }}


