apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cdm-data-pipeline-abc
  namespace: argocd
spec:
  project: cdm
  source:
    repoURL: "https://repourl.com/scm/ds/pipeline-deployment.git"
    targetRevision: main
    path: cdm-data-pipeline-pipeline-core/local-deployment/cdm-data-pipeline-abc-pipeline-core
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - ApplyOutOfSyncOnly=true
      - Replace=false
      - SkipDryRun=true
      - ManualSync=fase