apiVersion: v1
kind: ConfigMap
metadata:
  name: abc-elastic-sink
  namespace: abc-elastic-sink
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka.cdm-kafka.svc.cluster.local:9092"
  KAFKA_SCHEMA_REGISTRY: "https://schemaregistry.cdm-kafka.svc.cluster.local:8081"
  ELASTICSEARCH_HOST: "https://ELASTICURL.com:9200"
  ORGANIZATION_ID: "abc"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-elastic-sink
  namespace: abc-elastic-sink
  labels:
    app: abc-elastic-sink
  annotations:
    configmap.reloader.stakater.com/reload: "abc-elastic-sink"
    secret.reloader.stakater.com/reload: "abc-elastic-sink"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abc-elastic-sink
  template:
    metadata:
      labels:
        app: abc-elastic-sink
    spec:
      containers:
        - name: abc-elastic-sink
          image: ACCOUNTID.dkr.ecr.us-gov-east-1.amazonaws.com/betsie/pipeline/pipeline-core:IMAGE_TAG
          imagePullPolicy: Always
          args: 
            - "dsp"
            - "sink"
            - "cdm"
            - "--group"
            - "sink-cdm"
          envFrom:
            - secretRef:
                name: abc-elastic-sink
            - configMapRef:
                name: abc-elastic-sink
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
      restartPolicy: Always
      imagePullSecrets:
        - name: ecr-secret