apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cdm-cfk-secrets
  namespace: argocd
spec:
  project: cdm
  source:
    repoURL: "https://repourl.com/sacm/ds/pipeline-deployment.git"
    targetRevision: main
    path: external-secret/cdm-cfk-secrets
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - ApplyOutOfSyncOnly=true
      - Replace=false
      - SkipDryRun=true
      - ManualSync=fase