apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  destination:
    namespace: external-secrets
    server: "https://kubernetes.default.svc"
  project: cdm
  source:
    path: charts/external-secrets
    repoURL: "https://repourl.com/scm/ds/pipeline-deployment.git"
    targetRevision: main
    helm:
      releaseName: external-secrets
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - ApplyOutOfSyncOnly=true
      - Replace=false
      - SkipDryRun=true
      - ManualSync=fase