apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cdm
  namespace: argocd
spec:
  description: Example project for cdm purposes
  destinations:
    - namespace: '*' 
      server: '*'  
  sourceRepos:
    - '*' 
  clusterResourceWhitelist: 
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist: 
    - group: '*'
      kind: '*'