apiVersion: v1
kind: ConfigMap
metadata:
  name: xyz-axonius-processor
  namespace: xyz-axonius-processor
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka.cdm-kafka.svc.cluster.local:9071"
  KAFKA_SCHEMA_REGISTRY: "https://schemaregistry.cdm-kafka.svc.cluster.local:8081"
  ORGANIZATION_ID: "xyz"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-axonius-processor
  namespace: xyz-axonius-processor
  labels:
    app: xyz-axonius-processor
  annotations:
    configmap.reloader.stakater.com/reload: "xyz-axonius-processor"
    secret.reloader.stakater.com/reload: "xyz-axonius-processor"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xyz-axonius-processor
  template:
    metadata:
      labels:
        app: xyz-axonius-processor
    spec:
      containers:
        - name: xyz-axonius-processor
          image: ACCOUNTID.dkr.ecr.us-gov-east-1.amazonaws.com/pipeline/pipeline-core:pvs1.0
          args: 
            - "dsp"
            - "process"
            - "axon"
            - "--group"
            - "process-axon"
          envFrom:
            - secretRef:
                name: xyz-axonius-processor
            - configMapRef:
                name: xyz-axonius-processor
          resources:
             limits:
               cpu: "1"
               memory: "3Gi"
      restartPolicy: Always
      imagePullSecrets:
        - name: ecr-secret