{{- range .Values.topics }}
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: {{ .nameTopic }}
  namespace: {{ .nameSpace }}
spec:
  partitionCount: {{ .partitions }}
  replicas: {{ .replicationFactor }}
  configs:
    retention.ms: "{{ .retention }}"
    cleanup.policy: {{ .cleanup }}
  kafkaClusterRef:
    name: {{ .clusterName}}
  kafkaRest:
    authentication:
      type: bearer
      bearer:
        secretRef: {{ .secret }}
---
  {{- end }}
