apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-cluster-secret-store
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-gov-east-1  
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets