apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws-us-gov:iam::ACCOUNTID:role/cdm-eso-no-pvs-role