apiVersion: v1
kind: ConfigMap
metadata:
  name: xyz-axonius-connector
  namespace: xyz-axonius-connector
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka.cdm-kafka.svc.cluster.local:9071"
  KAFKA_SCHEMA_REGISTRY: "https://schemaregistry.cdm-kafka.svc.cluster.local:8081"
  AXONIUS_CONNECTION_URL: "https://AXONIUSURL.com/"
  ORGANIZATION_ID: "xyz"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: xyz-axonius-connector-cron
  namespace: xyz-axonius-connector
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template: 
        metadata:
          labels:
            app: xyz-axonius-connector
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: ecr-secret
          containers:
            - name: xyz-axonius-connector
              image: ACCOUNTID.dkr.ecr.us-gov-east-1.amazonaws.com/pipeline/pipeline-core:pvs1.0
              args: 
                - "dsp"
                - "connect"
                - "axon"
                # - "--force-first-time"
              envFrom:
                - secretRef:
                    name: xyz-axonius-connector
                - configMapRef:
                    name: xyz-axonius-connector
              # resources:
              #   limits:
              #     cpu: "1"
              #     memory: "3Gi"