apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: {{ .Values.namespace }}
  annotations:
    secret.reloader.stakater.com/reload: "{{ .Values.secrets.mdsClientSr }},{{ .Values.secrets.credential }},{{ .Values.secrets.mdsToken }}"
spec:
  image:
    application: {{ .Values.schemaregistry.image.application }}
    init: {{ .Values.schemaregistry.image.init }}
  license:
    secretRef: {{ .Values.schemaregistry.license.secretRef }}
  replicas: {{ .Values.schemaregistry.replicas }}
  authorization:
    type: {{ .Values.schemaregistry.authorization.type }}
    kafkaRestClassRef:
      name: {{ .Values.schemaregistry.authorization.kafkaRestClassRef.name }}
  configOverrides:
    server:
{{- range .Values.schemaregistry.configOverrides.server }}
      - "{{ . }}"
{{- end }}
    log4j:
{{- range .Values.schemaregistry.configOverrides.log4j }}
      - "{{ . }}"
{{- end }}
  dependencies:
    kafka:
      bootstrapEndpoint: {{ .Values.schemaregistry.dependencies.kafka.bootstrapEndpoint }}
      authentication:
        type: {{ .Values.schemaregistry.dependencies.kafka.authentication.type }}
        jaasConfig:
          secretRef: {{ .Values.schemaregistry.dependencies.kafka.authentication.jaasConfig.secretRef }}
      tls:
        enabled: {{ .Values.schemaregistry.dependencies.kafka.tls.enabled }}
    mds:
      endpoint: {{ .Values.schemaregistry.dependencies.mds.endpoint }}
      tokenKeyPair:
        secretRef: {{ .Values.schemaregistry.dependencies.mds.tokenKeyPair.secretRef }}
      authentication:
        type: {{ .Values.schemaregistry.dependencies.mds.authentication.type }}
        bearer:
          secretRef: {{ .Values.schemaregistry.dependencies.mds.authentication.bearer.secretRef }}
      tls:
        enabled: {{ .Values.schemaregistry.dependencies.mds.tls.enabled }}
  podTemplate:
    annotations: 
{{- toYaml .Values.schemaregistry.podTemplate.annotations | nindent 6 }}
  tls:
    autoGeneratedCerts: {{ .Values.schemaregistry.tls.autoGeneratedCerts }}
