---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: credential
  namespace: cdm-kafka
spec:
  refreshInterval: "60m"
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: credential
  data:
    - secretKey: ldap.txt
      remoteRef:
        key: /cdm-data-pipeline/cfk-credential
        property: ldap.txt
    - secretKey: plain-users.json
      remoteRef:
        key: /cdm-data-pipeline/cfk-credential
        property: creds-kafka-sasl-users.json
    - secretKey: plain.txt
      remoteRef:
        key: /cdm-data-pipeline/cfk-credential
        property: creds-client-kafka-sasl-user.txt