---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mds-token
  namespace: cdm-kafka
spec:
  refreshInterval: "60m"
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: mds-token
  data:
    - secretKey: mdsPublicKey.pem
      remoteRef:
        key: /cdm-data-pipeline/cfk-credential
        property: mdsPublicKey.pem
    - secretKey: mdsTokenKeyPair.pem
      remoteRef:
        key: /cdm-data-pipeline/cfk-credential
        property: mdsTokenKeyPair.pem