---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mds-client-krp
  namespace: cdm-kafka
spec:
  refreshInterval: "60m"
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: mds-client-krp
  data:
    - secretKey: bearer.txt
      remoteRef:
        key: /cdm-data-pipeline/cfk-credential
        property: krp-mds-client.txt