{{- if or .Values.abc_cdm_data_pipeline.deploy_environment.local.enabled .Values.abc_cdm_data_pipeline.deploy_environment.eks.enabled -}}
{{- if .Values.abc_cdm_data_pipeline.abc_elastic_sink.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.abc_cdm_data_pipeline.abc_elastic_sink.name }}
  namespace: {{ .Values.abc_cdm_data_pipeline.abc_elastic_sink.namespace }}
data:
  {{- range $key, $value := .Values.abc_cdm_data_pipeline.abc_elastic_sink.config }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}
{{- end }}
