{{- if or .Values.abc_cdm_data_pipeline.deploy_environment.local.enabled .Values.abc_cdm_data_pipeline.deploy_environment.eks.enabled }}
{{- if .Values.abc_cdm_data_pipeline.abc_cdm_processor.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.abc_cdm_data_pipeline.abc_cdm_processor.serviceAccount.name }}
  namespace: {{ .Values.abc_cdm_data_pipeline.abc_cdm_processor.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.abc_cdm_data_pipeline.abc_cdm_processor.serviceAccount.roleArn }}
{{- end }}
{{- end }}