{{- if or .Values.abc_cdm_data_pipeline.deploy_environment.local.enabled .Values.abc_cdm_data_pipeline.deploy_environment.eks.enabled }}
{{- if .Values.abc_cdm_data_pipeline.abc_armis_processor.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.abc_cdm_data_pipeline.abc_armis_processor.name }}
  namespace: {{ .Values.abc_cdm_data_pipeline.abc_armis_processor.namespace }}
  labels:
    app: {{ .Values.abc_cdm_data_pipeline.abc_armis_processor.name }}
  annotations:
    {{- toYaml .Values.abc_cdm_data_pipeline.abc_armis_processor.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.abc_cdm_data_pipeline.abc_armis_processor.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.abc_cdm_data_pipeline.abc_armis_processor.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.abc_cdm_data_pipeline.abc_armis_processor.name }}
    spec:
      containers:
        - name: {{ .Values.abc_cdm_data_pipeline.abc_armis_processor.name }}
          image: {{- if .Values.abc_cdm_data_pipeline.abc_armis_processor.image.enabled | default false }} {{ .Values.abc_cdm_data_pipeline.abc_armis_processor.image.repository }}:{{ .Values.abc_cdm_data_pipeline.abc_armis_processor.image.tag }}{{- else }} {{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}{{- end }}
          args:
            {{- range .Values.abc_cdm_data_pipeline.abc_armis_processor.commandArgs }}
            - {{ . | quote }}
            {{- end }}
          envFrom:
            {{- include "abc_armis_processor.envVars" . | nindent 12 }}
          {{- if not .Values.abc_cdm_data_pipeline.deploy_environment.local.enabled }}
          resources:
            limits:
              cpu: {{ .Values.abc_cdm_data_pipeline.abc_armis_processor.resources.limits.cpu }}
              memory: {{ .Values.abc_cdm_data_pipeline.abc_armis_processor.resources.limits.memory }}
          {{- end }}
      restartPolicy: {{ .Values.global.restartPolicy }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
{{- end }}
{{- end }}