tls:
  enabled: true
  fullchain: |
    -----BEGIN CERTIFICATE-----
    MIIFnDCCBISgAwIBAgIUPomK8u4hPlxfVtTyGQHd553h5sAwDQYJKoZIhvcNAQEL
    BQAwZDERMA8GA1UEBhMIVW5pdmVyc2UxDzANBgNVBAgTBlBhbmdlYTEOMAwGA1UE
    BxMFRWFydGgxDTALBgNVBAoTBEFjbWUxDjAMBgNVBAsTBU15T3JnMQ8wDQYDVQQD
    EwZUZXN0Q0EwHhcNMjUwMjA0MTEzMzAwWhcNMzAwMjAzMTEzMzAwWjBKMREwDwYD
    VQQGEwhVbml2ZXJzZTEPMA0GA1UECBMGUGFuZ2VhMQ4wDAYDVQQHEwVFYXJ0aDEU
    MBIGA1UEAwwLKi5jZG0ubG9jYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQDseqodAwZQRHjMln6DxUk52UXaLTzfNtzmABfwuHRzK6DoGZBcQA2XsOM9
    sQx32JDHzMb6uoLdwieh1zoyAJIHN8PYb9sAhr8ZK+6B8zDtPwSwmWNDn/+2JnxT
    NfOa+JXzaQNFibxSmmXd0JZj5eAyVWHrdsyfxw0FFSifowpNbU/Ft9cp//cawGGF
    0Hv/Q9cQE+cgH+gWCnsmBvI9im3ilTgsBEGHBTKHMcl4zad3+rpUKq6dhtQ1ytKy
    7ZwMBJlsHxeRFcKL334DiGdll6Wrk//Dgasms7vJHzgs4prJk6g7ouEdJcOJp4Pz
    OpJ5YxeKNh/Sg4ooffc9HjL0bXBtAgMBAAGjggJeMIICWjAOBgNVHQ8BAf8EBAMC
    BaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAw
    HQYDVR0OBBYEFH4kMKj0BOEIkvRsF6c6aV2te9wvMB8GA1UdIwQYMBaAFKXeqNe3
    ViJuN7BR6F2ueHGSprqDMIIB2QYDVR0RBIIB0DCCAcyCCyouY2RtLmxvY2Fsgh0q
    LmNvbmZsdWVudC5zdmMuY2x1c3Rlci5sb2NhbIInKi56b29rZWVwZXIuY29uZmx1
    ZW50LnN2Yy5jbHVzdGVyLmxvY2Fsgi0qLmtyYWZ0Y29udHJvbGxlci5jb25mbHVl
    bnQuc3ZjLmNsdXN0ZXIubG9jYWyCIyoua2Fma2EuY29uZmx1ZW50LnN2Yy5jbHVz
    dGVyLmxvY2FsgiIqLmxkYXAuY29uZmx1ZW50LnN2Yy5jbHVzdGVyLmxvY2FsgiBs
    ZGFwLmNvbmZsdWVudC5zdmMuY2x1c3Rlci5sb2NhbIILKi5jZG0ubG9jYWyCHyou
    ZGVzdGluYXRpb24uc3ZjLmNsdXN0ZXIubG9jYWyCKSouem9va2VlcGVyLmRlc3Rp
    bmF0aW9uLnN2Yy5jbHVzdGVyLmxvY2Fsgi8qLmtyYWZ0Y29udHJvbGxlci5kZXN0
    aW5hdGlvbi5zdmMuY2x1c3Rlci5sb2NhbIIlKi5rYWZrYS5kZXN0aW5hdGlvbi5z
    dmMuY2x1c3Rlci5sb2NhbIIqKi5yZXBsaWNhdG9yLmRlc3RpbmF0aW9uLnN2Yy5j
    bHVzdGVyLmxvY2FsMA0GCSqGSIb3DQEBCwUAA4IBAQBIIBC8pIAryB+/pag6evFx
    dc11NIkxd/xuhW5cQm/FEDTOMq2ifOOzMEytR8QhwyR2gWqzRnnl5WRzRzziOxF6
    4yM3/vR4meVPWu3Pcn/hYhTBdaFpJRnErE+zfwAC35TupFOzzoOfOJtmdJQY5Ju4
    ErIZhIQ6FDwfaqL8VvsMdbcJJpglpWhIG+Me9JzFTsN3lFtC0JRYPkld++rNfTVU
    /ohiQlEMM8FDP8p9YJwqOfPqWMhfzro05iAzpphWU4ETc10WVrV//rgyo0NcPv/W
    WMLSaHd5s3EfyRRaYM9SWYylcPz61fDOZ154S/+7tyfxQlxgaNHm22yPkOAtraYI
    -----END CERTIFICATE-----
  privkey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA7HqqHQMGUER4zJZ+g8VJOdlF2i083zbc5gAX8Lh0cyug6BmQ
    XEANl7DjPbEMd9iQx8zG+rqC3cInodc6MgCSBzfD2G/bAIa/GSvugfMw7T8EsJlj
    Q5//tiZ8UzXzmviV82kDRYm8Uppl3dCWY+XgMlVh63bMn8cNBRUon6MKTW1PxbfX
    Kf/3GsBhhdB7/0PXEBPnIB/oFgp7JgbyPYpt4pU4LARBhwUyhzHJeM2nd/q6VCqu
    nYbUNcrSsu2cDASZbB8XkRXCi99+A4hnZZelq5P/w4GrJrO7yR84LOKayZOoO6Lh
    HSXDiaeD8zqSeWMXijYf0oOKKH33PR4y9G1wbQIDAQABAoIBAGH/p3WkZj5nUcQ+
    7aj/3guqHcd/jcVXAA4UpdctKZz8zI7C4U9JgBiHxnQvZeJYjg8urpsDJe5uYmww
    PD6ye9Gf63pLSG+cZ58v1IRn2rPGtNPWjQteR+MdadI1/oEPWVzo/OEZZkC5GVPl
    +BzoC5PwTEb/EWd5XsznatFVCJTy1txi8MPc2xRly0j4kLFThK5Q/VqcFIbNLRKC
    AnCH4HUtyGZFA0UgAszF95V9tzvAwlf9EQpuRqLy/3vq1pSwWhTzjMD8kTZpOEE9
    Mreuw+Kg45QI+77dCqalX7co7VWWdsmaWYI95FuTV3XgrkZ5QHURNMhxMcEAXOFv
    L9aP+wECgYEA/lxEJJ8A3Jaa3h0COJUTuUyAS2vWPGAiCu0d60vfJvXmOA3RTmci
    3e8SfROHulXqMsws5AZ8utp869Wn5Ko8w461ZwNBJx21+plvkcr1jOCy7XgHtWuG
    G+HIdUnifJRb52OWzpLVucX9cRN8rlDgvz4bmo+6fzgsRVt6D51oFa0CgYEA7gDk
    OSg5rVeZv3u8Bvn6q8IlnqFMvgkpNJZPu6dXnyRGlWC0beCwkkoMkzfRev1Se2cB
    iumxXMAP3Yr4m3A7M7nS57gcxUDp1alBlVHtFaP4jLOD1yLKX6spy8U3vtS+rrxr
    GDf0Qt8zUMgecxBfqts7EeGABJMJ4SUopVOSncECgYBco8QZxmNs89kxvkT50Knf
    WhJ75amgUa70Zcn40ahTq0mO7tFlicC0LgeA0GUlo3bpy10qK4awEzVeO3GroakB
    3G8LNq87DOIjhFCTO+VUyt3ACXBdTe0JKKF2vlMj5nDWhHn/gJEg2RBmZ5+IaWKB
    pKAvGdvly9Kr7BY3q6+l/QKBgQDmJuiLuTFlRfQArlfaazwTgjA84QBEOLmnB7/c
    2GssErlK1HRGWOSG4qKcbnrdM0Di4m4kde40oen1s+DK91HYqFaiC3GO8kHtgrpP
    +iSJK8I71ZClpxgKQYuuaG2K1VH7yWrKxbkoPYzzDkIbxPauU0gg926Dfeks1nEi
    xtleQQKBgQDMNWPyRg1+nNhoeJOPBGxuRfU2HmP1IldKf308Otsk3CSaqnln6L98
    /+MxIbbdc4RaloZaQ1LrkxCx5raDeZZ6nHUVmR6qAaQFM7PEVNpTLd9bXjFUX85N
    jFrpWdYhJSBYV32b7xkiRoMMI4i193sfAtYs3bxaXgHywY+tAxVJ5A==
    -----END RSA PRIVATE KEY-----
  cacerts: |
    -----BEGIN CERTIFICATE-----
    MIIDmDCCAoCgAwIBAgIUY7niGuGZMvaqbsZwB9OTzdYBuQwwDQYJKoZIhvcNAQEL
    BQAwZDERMA8GA1UEBhMIVW5pdmVyc2UxDzANBgNVBAgTBlBhbmdlYTEOMAwGA1UE
    BxMFRWFydGgxDTALBgNVBAoTBEFjbWUxDjAMBgNVBAsTBU15T3JnMQ8wDQYDVQQD
    EwZUZXN0Q0EwHhcNMjUwMjA0MTEzNzAwWhcNMzAwMjAzMTEzNzAwWjBkMREwDwYD
    VQQGEwhVbml2ZXJzZTEPMA0GA1UECBMGUGFuZ2VhMQ4wDAYDVQQHEwVFYXJ0aDEN
    MAsGA1UEChMEQWNtZTEOMAwGA1UECxMFTXlPcmcxDzANBgNVBAMTBlRlc3RDQTCC
    ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANqGs4cyDkrPXluRS14liNaO
    a6PH8Ffc+FoFab0Sz8tcFWv9VDNI35LQS5w/3XQZXkyS33ViX4k/GSIQIvLoGllE
    1cNh6ZwlMxe1mApPYe306OEgy6RLNvkyZoanF/BHGCxkGbY584Y2QsICWAdKDtFU
    VZuUBDyx2lO2NJalb0BXu1XR1R/TPgn4EPprbC7b3U4trsvvBjJBy5A2XYl7gM8N
    ykv+NH0YbjoSJf+zTWftwR9dE7sbZIrlqyoMFUFcVaLU7xigNo4X44DBXanUU/UW
    fUXO5ulweQkoxdyfl+b7NNXK/lNWBpKPolGyzA7VBwx/PgA1RwO0ng8VaAEGkxcC
    AwEAAaNCMEAwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0O
    BBYEFFqy+N00WMkbGxztRD6IjSsClrH/MA0GCSqGSIb3DQEBCwUAA4IBAQAlJ87R
    679+nfJ26aXiKpM0VQczOHCvuCMzLpR33c1gI2extj8IYu429GMQOHIgNhJL6H80
    2Dhg8a+xZaqXY8h0JFShT5aVCS4QmDpChY2WLwftKacIVG7tdxBOCKgUipr0bHrw
    16qqKv+K2ZRxALFOrf3iSdxWt0NaQq2S9SrelV0gCC8KVYays6zit2wXLB3LNV22
    QA/hNQ8JawEBAvNJAS5348XppxeFAejYcEUBc1d6OPT5m2Fu+Qmuqudacilq5KFz
    tf1xCjk6+KZ55T6U97bZQ6hcVqXjtb8MxjsXklXWVMYxSVrB4T88CzdRwc38BNo2
    YtMMz32bANYCoAbH
    -----END CERTIFICATE-----


