{{- if or .Values.abc_cdm_data_pipeline.deploy_environment.local.enabled .Values.abc_cdm_data_pipeline.deploy_environment.eks.enabled -}}
{{- if .Values.abc_cdm_data_pipeline.abc_quality_cdm_processor.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.abc_cdm_data_pipeline.abc_quality_cdm_processor.name }}
  namespace: {{ .Values.abc_cdm_data_pipeline.abc_quality_cdm_processor.namespace }}
spec:
  refreshInterval: {{ .Values.abc_cdm_data_pipeline.abc_quality_cdm_processor.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.abc_cdm_data_pipeline.abc_quality_cdm_processor.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.abc_cdm_data_pipeline.abc_quality_cdm_processor.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.abc_cdm_data_pipeline.abc_quality_cdm_processor.externalSecret.target.name }}
    creationPolicy: {{ .Values.abc_cdm_data_pipeline.abc_quality_cdm_processor.externalSecret.target.creationPolicy }}
  data:
    {{- include "abc_quality_cdm_processor.externalSecret.data" . | nindent 2 }}
{{- end -}}
{{- end }}