apiVersion: v1
kind: Secret
metadata:
  name: mds-client-c3
  namespace: cdm-kafka
type: Opaque
stringData:
  bearer.txt: REPLACE_WITH_ACTUAL_VALUE

---
apiVersion: v1
kind: Secret
metadata:
  name: mds-client-connect
  namespace: cdm-kafka
type: Opaque
stringData:
  bearer.txt: REPLACE_WITH_ACTUAL_VALUE

---
apiVersion: v1
kind: Secret
metadata:
  name: mds-client-erp
  namespace: cdm-kafka
type: Opaque
stringData:
  bearer.txt: REPLACE_WITH_ACTUAL_VALUE

---
apiVersion: v1
kind: Secret
metadata:
  name: mds-client-krp
  namespace: cdm-kafka
type: Opaque
stringData:
  bearer.txt: REPLACE_WITH_ACTUAL_VALUE

---
apiVersion: v1
kind: Secret
metadata:
  name: mds-client-ksql
  namespace: cdm-kafka
type: Opaque
stringData:
  bearer.txt: REPLACE_WITH_ACTUAL_VALUE

---
apiVersion: v1
kind: Secret
metadata:
  name: mds-client-sr
  namespace: cdm-kafka
type: Opaque
stringData:
  bearer.txt: REPLACE_WITH_ACTUAL_VALUE

---
apiVersion: v1
kind: Secret
metadata:
  name: mds-token
  namespace: cdm-kafka
type: Opaque
stringData:
  mdsPublicKey.pem: REPLACE_WITH_ACTUAL_VALUE
  mdsTokenKeyPair.pem: REPLACE_WITH_ACTUAL_VALUE

---
apiVersion: v1
kind: Secret
metadata:
  name: credential
  namespace: cdm-kafka
type: Opaque
stringData:
  ldap.txt: REPLACE_WITH_ACTUAL_VALUE
  plain-users.json: REPLACE_WITH_ACTUAL_VALUE
  plain.txt: REPLACE_WITH_ACTUAL_VALUE

---
apiVersion: v1
kind: Secret
metadata:
  name: ca-pair-sslcerts
  namespace: cdm-kafka
type: kubernetes.io/tls
stringData:
  tls.crt: REPLACE_WITH_ACTUAL_VALUE
  tls.key: REPLACE_WITH_ACTUAL_VALUE

---
apiVersion: v1
kind: Secret
metadata:
  name: rest-credential
  namespace: cdm-kafka
type: Opaque
stringData:
  bearer.txt: REPLACE_WITH_ACTUAL_VALUE
  basic.txt: REPLACE_WITH_ACTUAL_VALUE

