apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-cluster-secret-store
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.global.aws.region }}
      {{- if eq .Values.global.aws.env "eks" }} 
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
      {{- else if eq .Values.global.aws.env "local" }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: AWS_ACCESS_KEY_ID
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: aws-credentials
            key: AWS_SECRET_ACCESS_KEY
            namespace: external-secrets
      {{- end }}