---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ca-pair-sslcerts
  namespace: cdm-kafka
spec:
  refreshInterval: "60m"
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: ca-pair-sslcerts
  data:
    - secretKey: tls.crt
      remoteRef:
        key: /cdm-data-pipeline/cfk-credential
        property: ca.pem
    - secretKey: tls.key
      remoteRef:
        key: /cdm-data-pipeline/cfk-credential
        property: ca-key.pem